version: 2

mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'Approval check'
    validate:
      - do: approvals
        min:
          count: 1
        limit:
          users: [ 'VersusXX', '7gambit7', 'AlexandrKudrya']